### ISSUE TITLE
MariaDB Data too long for column 'position'

### ISSUE THREAD

**Issue by sandrokeil** [prooph/event-store-benchmarks#6]
This error should not happend

```
projection 139875962182376 used 54.199523925781 seconds, avg 46.12586640841 events/second
Class 'Prooph\EventStore\Pdo\Exception\RuntimeException' not found
#0 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(583): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->persist()
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(488): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->handleStreamWithSingleHandler('blog-da7f61bd-d...', Object(Prooph\EventStore\Pdo\PdoStreamIterator))
#2 /app/src/AllProjector.php(48): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#3 [internal function]: Prooph\EventStoreBenchmarks\AllProjector->run()
#4 {main}
```

**Comment by codeliner** [comment]
Patching the [PdoEventStoreProjector](https://github.com/prooph/event-store-benchmarks/blob/master/src/benchmark.php#L34) seems not to work?

**Comment by sandrokeil** [comment]
The real error is
```
Error 22001. 
Error-Info: Data too long for column 'position' at row 1
#0 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(827): Prooph\EventStore\Pdo\Exception\RuntimeException::fromStatementErrorInfo(Array)
#1 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(583): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->persist()
#2 /app/vendor/prooph/pdo-event-store/src/Projection/PdoEventStoreProjector.php(488): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->handleStreamWithSingleHandler('blog-b1935e9f-d...', Object(Prooph\EventStore\Pdo\PdoStreamIterator))
#3 /app/src/AllProjector.php(48): Prooph\EventStore\Pdo\Projection\PdoEventStoreProjector->run()
#4 [internal function]: Prooph\EventStoreBenchmarks\AllProjector->run()
#5 {main}
```

**Comment by prolic** [comment]
We need to change from TEXT to LONGTEXT. That requires a db migration and cannot be done without downtime. That's a damn bug!

In MySQL the problem is not there, because JSON(B) is an extension of LONGTEXT already.

When a db change is needed here (with downtime!) we probably should use this for improving uuid column as well. We could provide a script that migrates existing event store databases. Depending on the amount of streams, this script could run a little, so without downtime this upgrade is not possible, but as we have seen here, it's needed (at least with mariadb).

Thoughts?

@codeliner  @sandrokeil @bweston92 @oqq

**Comment by bweston92** [comment]
We can update table schema without down time just a bit of latency using
ALTER TABLE?

**Comment by prolic** [comment]
That would probably work for changing TEXT => LONGTEXT, but this would not work with improved uuid columns, because the SQL query has to be changed as well.

**Comment by bweston92** [comment]
In what way are the uuid columns being updated? Also you can describe the
table and perform the correct query until the next major release.

**Comment by prolic** [comment]
For postgres, there is a UUID type that we can use. For MySQL someone linked this blog post: https://www.percona.com/blog/2014/12/19/store-uuid-optimized-way/

Note: I have not yet tried it myself.

**Comment by prolic** [comment]
Another note: In this blog post linked above, they use uuid v1.

**Comment by prolic** [comment]
see also https://github.com/ramsey/uuid/pull/118

**Comment by sandrokeil** [comment]
@prolic Looks like nobody uses MariaDB at the moment, because this bug was not reported.

**Comment by prolic** [comment]
Maybe, but it also comes up with some streams, with only 2-5 streams no
problem.

**Comment by oqq** [comment]
Since it would be a bc break if we change the database layout, I would prefer to add new storage strategies and deprecate previous ones instead of removing. This would lead into work and some duplicated code. But every user has the chance to run his application without any downtime after composer update.

We should simply add a migration sql file, add a version to the strategies and have and provide a way for migrations in future releases. This issue would not be the last one for the database structures. Maybe it makes sense to add all queries to the PersistenceStrategy interface. (Implemented in a non bc-break way for now)

Also i am with @sandrokeil MariaDB is currently not really used.

**Comment by sandrokeil** [comment]
@oqq Good idea with new strategy/deprecating, but I'm not sure if we can and should provide migration stuff. I guess it's to difficult, someone uses Doctrine Migrations, others another tool ...

**Comment by oqq** [comment]
Sure, but we can add a simple sql file in scripts folder without implementation. A readme file for usages of this script should be enough.
